### ISSUE TITLE
ReferenceError: window is not defined at Object.

### ISSUE THREAD

**Issue by lisakhr** [bem/gemini#102]
Hi!
I installed gemini and tried to run examples from tutorial and got the error:
<b>"ReferenceError: window is not defined at Object. (~\gemini\node_modules\gemini\lib\browser\client-scripts\gemini.coverage.js:129:3) at Module._compile (module.js:456:26) at Object.Module._extensions..js (module.js:474:10) at Module.load (module.js:356:32) at Function.Module._load (module.js:312:12) at Module.require (module.js:364:17) at require (module.js:380:17) at requireWithNoCache (~\node_modules\gemini\lib\gemini.js:18:18) at Array.forEach (native) at ~\node_modules\gemini\lib\gemini.js:60:26"</b>

Am i doing smth wrong?

**Comment by SevInf** [comment]
Can you please provide more info about which OS and node versions are you using?

**Comment by lisakhr** [comment]
OS: win 8.1
node: 0.10.35

**Comment by SevInf** [comment]
Can you also point me to example your are using and the command you are running?

**Comment by lisakhr** [comment]
I tried config:
rootUrl: http://yandex.com
gridUrl: http://localhost:4444/wd/hub

browsers:
  chrome:
    browserName: chrome
    version: "37.0"

  firefox:
    browserName: firefox
    version: "31.0"


and test file:

var gemini = require('gemini');

gemini.suite('yandex-search', function(suite) {
    suite.setUrl('/')
        .setCaptureElements('.main-table')
        .capture('plain')
        .capture('with text', function(actions, find) {
            actions.sendKeys(find('.input__control'), 'hello gemini');
        });
});


command: gemini gather {path to project folder}
tried both - selenium server and phantomJS
Also tried gemini-gui - the same result

**Comment by SevInf** [comment]
Can you try to launch it using path to test file instead of a path to project folder and report the result?

**Comment by lisakhr** [comment]
When I launch it using a path to file - there is no error with gemini, but I have another problem like "environment you requested was unavailable." 
Selenium Server (version 2.42.2) is launched localhost. In gemini-config - firefox version 30.0, which according to 
https://docs.google.com/spreadsheetsd/1ro2XjjJk428HdIjFm3ESWhiKJiTmBkR_BiRVKqHlEms
/edit#gid=0
is supported by selenium server 2.42.2.
Thanks for your help!

**Comment by SevInf** [comment]
Thanks.
About the original problem, make sure the folder you are pointing gemini to contains only gemini tests. There is no way to distinguish `JS` with a tests in it from any other `JS` files, so when you pointing it to a folder, `gemini` tries to load all `.js` files it founds there.

For the second problem, make sure you have Firefox 30 installed – selenium can not automatically download and install browsers, it only can launch and drive what already installed on your machine.

**Comment by lisakhr** [comment]
My project folder contains a config-file, one test file and "node-modules" folder, which was created by local installation of gemini. 
Second problem - solved.

**Comment by SevInf** [comment]
Yes, I believe its the problem – `gemini` descends into `node_modules` directory and tries to load `*.js` files it encounters there.
The easiest workaround for you should be putting the tests into some some sub-folder of the project and point gemini to it instead of project root. If your subfolder name will be `gemini` you won't have to specify a folder at all – we are loading tests from there by default.

**Comment by lisakhr** [comment]
It's working! Thanks a lot!
