### ISSUE TITLE
publish latest to NPM

### ISSUE THREAD

**Issue by wrench7** [bem/gemini#124]
Hi, firstly thanks for a great visual diffing framework!

I installed gemini globally using npm, but would like to use the tolerance property that was recently re-added. Is it possible to publish the latest changes into the npm repo please?

**Comment by SevInf** [comment]
Hi.
Thanks for your interest. We are going to publish new release in 1-2 days. Most likely it will be `v0.10-beta`.

**Comment by SevInf** [comment]
It is now published at `npm` as `v0.10.0-beta.1`

Note, that this version is tagged as `prerelase` on `npm`,  so existing versions won't be updated automatically.  You need to explicitly specify the version using either `npm install gemini@prerelease` or `npm install gemini@0.10.0-beta.1`.

Final 0.10.0 is expected to be released in 1-2 weeks.
