### ISSUE TITLE
serialize

### ISSUE THREAD

**Issue by j0tunn** [bem/gemini#126]
как-то у меня имя `searialize` ассоциируется с преобразованием в строку

|commit|file reference|pull request|   |
|------|--------------|------------|---|
|d011946e828dd356a0feb3f9e44a3ab41819f621|[lib/browser/client-scripts/gemini.js#L89](https://github.com/bem/gemini/blob/d011946e828dd356a0feb3f9e44a3ab41819f621/lib/browser/client-scripts/gemini.js#L89)| #125 |[![#125](http://app.review.ninja/assets/images/icon-alt-36.png)](http://app.review.ninja/bem/gemini/pull/125)|

**Comment by SevInf** [comment]
Ассоциация неправильная: http://en.wikipedia.org/wiki/Serialization
